import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import fs from 'node:fs';
import path from 'node:path';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  integrationSidebar: [{type: 'autogenerated', dirName: 'integration'}],
  usecaseSidebar: [{type: 'autogenerated', dirName: 'usecase'}],
  codexstartSidebar: [{type: 'autogenerated', dirName: 'codexstart'}],
  pluginSkillHandbookSidebar: [
    {type: 'autogenerated', dirName: 'plugin-skill-handbook'},
  ],
};

for (const directory of fs.readdirSync(path.join(__dirname, 'docs'), {withFileTypes: true})) {
  if (!directory.isDirectory() || ['integration', 'usecase', 'codexstart', 'plugin-skill-handbook'].includes(directory.name)) continue;
  sidebars[`${directory.name}Sidebar`] = [{type: 'autogenerated', dirName: directory.name}];
}

export default sidebars;
